name = "burmemark-worker"
main = "worker.js"
compatibility_date = "2024-09-01"

# workers.dev အောက်မှာ default URL ရမယ်
workers_dev = true

# frontend GitHub Pages က fetch ခေါ်မယ်ဆိုတော့ route မသတ်မှတ်လည်းရ
# custom domain သုံးမယ်ဆို routes ထဲမှာ ထည့်

[vars]
APP_NAME = "Burme Mark Ai"

# Secrets ကို ဒီမှာမထည့်ပါ
# ထည့်ချင်ရင် => wrangler secret put OPENAI_API_KEY
#                wrangler secret put STABILITY_KEY
